### ISSUE TITLE
GDExtension interface was reworked in Godot 4.1

### ISSUE THREAD

**Issue by ioncorimenia** [gilzoide/hello-gdextension#3]
As of godotengine/godot@9b9482d, the `GDExtensionInterface` struct was retired in favour of only passing a pointer to `gdextension_get_proc_address`. This makes the examples in `1.hello-c` no longer applicable to the latest Godot version.

**Comment by gilzoide** [comment]
Oh, you're right, thanks for the report! I am aware of this change in 4.1, but this repo is a little bit left aside for now.
I'll likely fix it at some point, but I won't promise anything. If you'd like, you can open a PR fixing it (no pressure, do it only if you feel like it).

In the meantime, if you're trying to use GDExtension from C, you may try the [GDExtension Lite](https://github.com/gilzoide/gdextension-lite) project, which takes care of all the bindings boilerplate (it is Godot 4.1+ compatible).

**Comment by gilzoide** [comment]
It took a while for me to take some time to update the tutorial, but here it is, fixed!
Thanks again, cheers! \o/
