### ISSUE TITLE
error in hellogdextension code

### ISSUE THREAD

**Issue by pkartsev** [gilzoide/hello-gdextension#5]
https://github.com/gilzoide/hello-gdextension/blob/main/1.hello-c/README.md

(EDIT: I mean error in the file 'hello.gdextension' shown in README.md, listing 8 )

```
linux.x86_64 = "libhello-gdextensions.so"
windows.x86_64 = "hello-gdextensions.dll"
macos = "libhello-gdextensions.dylib"
```

should be

```
linux.x86_64 = "libhello-gdextension.so"
windows.x86_64 = "hello-gdextension.dll"
macos = "libhello-gdextension.dylib"
```

(without character "s")

as the library file compiled by scons is named libhello-gdextension.so (in case of Linux target)

Otherwise running godot line gives error with strange path changes:

```
ERROR: Can't open dynamic library: {Godot project folder}/libhello-gdextensions.so. 
Error: /home/USER/bin/godot-4.2.1/../lib/libhello-gdextensions.so: cannot open shared object file: No such file or directory.
```

Cheers!

**Comment by gilzoide** [comment]
Wow, true that! I made it right in the [example file](https://github.com/gilzoide/hello-gdextension/blob/main/1.hello-c/hello.gdextension#L6-L8), but wrong [in the article](https://github.com/gilzoide/hello-gdextension/blob/main/1.hello-c/README.md?plain=1#L113-L115) 😅
Thanks for spotting that out, I'll fix this right away!
